wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.1
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736500656.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 53
      - 55
      - 77
      3:
      - 7
      - 13
      - 23
      4: 3.8.1
      5: 0.16.5
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
    - 1: Train Loss (Phase 1)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 1)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 1)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 1)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 2)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 2)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 2)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 2)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 3)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 3)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 3)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 3)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 4)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 4)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 4)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 4)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 5)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 5)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 5)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 5)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 6)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 6)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 6)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 6)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 7)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 7)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 7)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 7)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 8)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 8)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 8)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 8)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 9)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 9)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 9)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 9)
      5: 1
      6:
      - 1
      - 3
    - 1: Train Loss (Phase 10)
      5: 1
      6:
      - 1
      - 3
    - 1: Train ACC (Phase 10)
      5: 1
      6:
      - 1
      - 3
    - 1: Test Loss (Phase 10)
      5: 1
      6:
      - 1
      - 3
    - 1: Test ACC (Phase 10)
      5: 1
      6:
      - 1
      - 3
seed:
  desc: null
  value: 42
data_path:
  desc: null
  value: ../data/sp500/
mode:
  desc: null
  value: train
key:
  desc: null
  value: 420ba3a37f4de92bf7fcf501ab5b24877d1d9cc1
d:
  desc: null
  value: 32
nh:
  desc: null
  value: 4
dr:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0001
edges:
  desc: null
  value: 64
fusion:
  desc: null
  value: sum
